import {
  beerbotclub,
  visibilitytech,
  landpages,
  food_ecomerce,
  finance_personal,
  dashboard,
  bmfund,
  screenMagic,
} from "../assets/projectImages";
export const ProjectsListData = [
  {
    id: 7,
    name: "Finance Personal",
    imageSrc: finance_personal,
    techs: "VueJS, Css ",
    github: "https://github.com/shaggyt85/Finanzas_personales",
    web: "https://finanzas-personales-six.vercel.app",
  },
  {
    id: 6,
    name: "Food E-commerce",
    imageSrc: food_ecomerce,
    techs: "ReactJS, Tailwinds, Motion ",
    github: "https://github.com/shaggyt85/crm_eccommerce",
    web: "https://eccommerce-test.vercel.app",
  },
  {
    id: 3,
    name: "BeerbotClub",
    imageSrc: beerbotclub,
    techs: "ReactJS, Css3, Web3 js ",
    github: "#",
    web: "https://beerbot.club",
  },
  {
    id: 4,
    name: "Dashboard Api-full",
    imageSrc: bmfund,
    techs: "Reactjs, ExpressJS",
    github: "#",
    web: "#",
  },
  {
    id: 2,
    name: "VisibilityTech",
    imageSrc: visibilitytech,
    techs: "Html5, Css3, Bootstrap ",
    github: "#",
    web: "https://visibilitytech.cl",
  },
  {
    id: 5,
    name: "Dashboard E-commerce",
    imageSrc: dashboard,
    techs: "Nextjs ",
    github: "https://github.com/shaggyt85/react-shop-admin",
    web: "https://github.com/shaggyt85/react-shop-admin",
  },
  {
    id: 1,
    name: "LandPages galery",
    imageSrc: landpages,
    techs: "Javascript Vainilla",
    github: "https://github.com/shaggyt85/async_landpages",
    web: "https://github.com/shaggyt85/async_landpages",
  },
  {
    id: 8,
    name: "ScreenMagic",
    imageSrc: screenMagic,
    techs: "Html5, Css3, Javascript",
    github: "https://github.com/shaggyt85/ScreenMagic",
  },
];
