/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: victory_mirosya (https://sketchfab.com/victory_mirosya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fox-f372c04de44640fbb6a4f9e4e5845c78
Title: Fox
*/
/**
 * Componente Fox
 *
 * Este componente renderiza un modelo 3D de un zorro utilizando la biblioteca react-three/drei.
 * El modelo 3D se carga desde un archivo .glb y se manejan las animaciones del modelo.
 *
 * @component
 * @param {Object} props - Las propiedades que se pasan al componente.
 * @param {string} props.currentAnimation - La animación actual que se debe reproducir.
 */
/* eslint-disable react/no-unknown-property */
import { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import scene from "../../assets/3d/fox.glb";
import { AnimationHandler } from "./AnimationHandler";
import { SkinnedMesh } from "./SkinnedMesh";
export const Fox = ({ currentAnimation, ...props }) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <AnimationHandler actions={actions} currentAnimation={currentAnimation} />
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        {["Object_7", "Object_8", "Object_9", "Object_10", "Object_11"].map(
          (name) => (
            <SkinnedMesh
              key={name}
              name={name}
              nodes={nodes}
              materials={materials}
            />
          )
        )}
      </group>
    </group>
  );
};
